# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

name: Build conda package
on:
  push:

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.CONFIG }}
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      max-parallel: 50
      matrix:
        include:
          - CONFIG: win_arm64_cl_version19.29.30139cross_target_platformwin-64runtime_version14.29.30139sha256296F96CD102250636BCD23AB6E6CF70935337B1BBB3507FE8521D8D9CFAA932Fupdate_version11uuidb929b7fe-_hea466f03
            STORE_BUILD_ARTIFACTS: True
            SHORT_CONFIG: win_arm64_cl_version19.29.30139cross_tar_hea466f03
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: win_arm64_cl_version19.44.35207cross_target_platformwin-64runtime_version14.44.35208sha256D62841375B90782B1829483AC75695CCEF680A8F13E7DE569B992EF33C6CD14Aupdate_version14uuid40b59c73-_h369391eb
            STORE_BUILD_ARTIFACTS: True
            SHORT_CONFIG: win_arm64_cl_version19.44.35207cross_tar_h369391eb
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: win_arm64_cl_version19.44.35207cross_target_platformwin-arm64runtime_version14.44.35208sha2561DB5C25643A3A4E4C99BFD0D0931A702A49C73DADC4B30672687F32188C1724Cupdate_version14uuid40b59c_hb89f60bd
            STORE_BUILD_ARTIFACTS: True
            SHORT_CONFIG: win_arm64_cl_version19.44.35207cross_tar_hb89f60bd
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: win_arm64_cl_version19.51.36231cross_target_platformwin-64runtime_version14.51.36231sha25690E48ADE404E4576D023ABFA374F323555F233982A8805EA9AC63DCA9491A16Bupdate_version1uuidc1bd4f2c-3_h096b8484
            STORE_BUILD_ARTIFACTS: True
            SHORT_CONFIG: win_arm64_cl_version19.51.36231cross_tar_h096b8484
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: win_arm64_cl_version19.51.36231cross_target_platformwin-arm64runtime_version14.51.36231sha256E912E9E653A5295A382BF86521F9B852AEECA823F4A9BF10BB2FBA7DD9445288update_version1uuid0dd156a_h2b1107f0
            STORE_BUILD_ARTIFACTS: True
            SHORT_CONFIG: win_arm64_cl_version19.51.36231cross_tar_h2b1107f0
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
    steps:

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Build on Linux
      id: build-linux
      if: matrix.os == 'ubuntu'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
        CI: github_actions
        CONDA_FORGE_DOCKER_RUN_ARGS: "${{ matrix.CONDA_FORGE_DOCKER_RUN_ARGS }}"
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        if [[ "$(uname -m)" == "x86_64" ]]; then
          echo "::group::Configure binfmt_misc"
          docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
        fi
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        echo "::endgroup::"
        ./.scripts/run_docker_build.sh

    - name: Build on macOS
      id: build-macos
      if: matrix.os == 'macos'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        CI: github_actions
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        ./.scripts/run_osx_build.sh

    - name: Build on windows
      id: build-windows
      if: matrix.os == 'windows'
      shell: cmd
      run: |
        set "flow_run_id=github_%GITHUB_RUN_ID%"
        set "remote_url=https://github.com/%GITHUB_REPOSITORY%"
        set "sha=%GITHUB_SHA%"
        call ".scripts\run_win_build.bat"
      env:
        # default value; make it explicit, as it needs to match with artefact
        # generation below. Not configurable for now, can be revisited later
        CONDA_BLD_PATH: C:\bld
        MINIFORGE_HOME: ${{ contains(runner.arch, 'ARM') && 'C' || 'D' }}:\Miniforge
        PYTHONUNBUFFERED: 1
        CONFIG: ${{ matrix.CONFIG }}
        CI: github_actions
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}

    - name: Determine build outcome
      # this is to merge the status of the linux/osx/win builds into
      # something we can easily reuse during artefact generation
      id: determine-status
      if: ${{ always() }}
      shell: bash
      env:
        OS: ${{ matrix.os }}
      run: |
        if [[ "$OS" == "ubuntu" ]]; then
          STATUS=${{ steps.build-linux.outcome }}
        elif [[ "$OS" == "macos" ]]; then
          STATUS=${{ steps.build-macos.outcome }}
        elif [[ "$OS" == "windows" ]]; then
          STATUS=${{ steps.build-windows.outcome }}
        fi
        if [ -z "$STATUS" ]; then
          # steps that never ran will have empty status
          STATUS="cancelled"
        fi
        echo "status=$STATUS" >> $GITHUB_OUTPUT

    - name: Prepare conda build artifacts
      continue-on-error: true
      id: prepare-artifacts
      shell: bash
      # we do not want to trigger artefact creation if the build was cancelled
      if: ${{ always() && steps.determine-status.outputs.status != 'cancelled' && matrix.STORE_BUILD_ARTIFACTS }}
      env:
        CI: github_actions
        CONFIG: ${{ matrix.CONFIG }}
        SHORT_CONFIG: ${{ matrix.SHORT_CONFIG }}
        JOB_STATUS: ${{ steps.determine-status.outputs.status }}
        OS: ${{ matrix.os }}
      run: |
        export CI_RUN_ID=$GITHUB_RUN_ID
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export ARTIFACT_STAGING_DIR="$GITHUB_WORKSPACE"
        if [ $OS == "macos" ]; then
          export CONDA_BLD_PATH="${MINIFORGE_HOME:-${HOME}/miniforge3}/conda-bld"
        elif [ $OS == "windows" ]; then
          # this needs to be consistent with build step, see above
          export CONDA_BLD_PATH="C:\\bld"
        else
          export CONDA_BLD_PATH="build_artifacts"
        fi
        # Archive everything in CONDA_BLD_PATH except environments
        # Archive the CONDA_BLD_PATH environments only when the job fails
        # Use different prefix for successful and failed build artifacts
        # so random failures don't prevent rebuilds from creating artifacts.
        if [ $JOB_STATUS == "failure" ]; then
          export BLD_ARTIFACT_PREFIX="conda_artifacts"
          export ENV_ARTIFACT_PREFIX="conda_envs"
        else
          export BLD_ARTIFACT_PREFIX="conda_pkgs"
        fi
        if [ $OS == "windows" ]; then
          pwsh -Command ". '.scripts/create_conda_build_artifacts.bat'"
        else
          ./.scripts/create_conda_build_artifacts.sh
        fi

    - name: Store conda build artifacts
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      if: ${{ always() && steps.prepare-artifacts.outcome == 'success' }}
      with:
        name: ${{ steps.prepare-artifacts.outputs.BLD_ARTIFACT_NAME }}
        path: ${{ steps.prepare-artifacts.outputs.BLD_ARTIFACT_PATH }}
        retention-days: 14
      continue-on-error: true

    - name: Store conda build environment artifacts
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      # only relevant if build failed, see above
      if: ${{ always() && steps.determine-status.outputs.status == 'failure' && steps.prepare-artifacts.outcome == 'success' }}
      with:
        name: ${{ steps.prepare-artifacts.outputs.ENV_ARTIFACT_NAME }}
        path: ${{ steps.prepare-artifacts.outputs.ENV_ARTIFACT_PATH }}
        retention-days: 14
      continue-on-error: true